In [1]:
X = [[12,9,3],
    [4,5,6],
    [7,8,3]]

Y = [[6,8,1,3],
    [5,7,3,4],
    [0,6,9,1]]

In [5]:
[i for i in zip(*X)]

[(12, 4, 7), (9, 5, 8), (3, 6, 3)]

In [ ]:
def multiplyTwoArray(a: list, b: list) -> list:
    return sum([i*j for i,j in zip(a, b)]) 

def multiply_two_matrices(X: list[list], Y: list[list]) -> list[list]:
    result = [multiply_two_matrices(X[])]
    return result

In [6]:
import numpy as np

In [12]:
a = np.array(X)
b = np.array(Y)

print(a)
print(b)

[[12  9  3]
 [ 4  5  6]
 [ 7  8  3]]
[[6 8 1 3]
 [5 7 3 4]
 [0 6 9 1]]


In [13]:
print(np.dot(a, b))

[[117 177  66  75]
 [ 49 103  73  38]
 [ 82 130  58  56]]
